bpms:
  uri: http://${BPMS_HOST:localhost}:${BPMS_PORT:9090}/engine-rest

server:
  port: ${SERVER_PORT:8090}

external-services:
  documents:
    host: http://host.docker.internal
    port: 8089
  tasks:
    host: http://host.docker.internal
    port: 8092
  notifications:
    host: http://213.108.129.175
    port: 8100

logging:
  level:
    root: INFO
