server:
  port: ${SERVER_PORT:8081}

camunda:
  uri: http://${CAMUNDA_HOST:localhost}:${CAMUNDA_PORT:8100}/engine-rest

spring:
  jackson:
    default-property-inclusion: NON_NULL
  #https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
  jpa:
    open-in-view: false